version: "3.8"

services:
  postgres:
    image: postgres:15 # or specify a specific version
    container_name: WLT_PG_DB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wlt_dev_db
    ports:
      - "9000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wlt_system_network

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  wlt_system_network:
    driver: bridge
