user:
  service:
    base-url: ${USER_SERVICE_URL}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${USER_SERVICE_URL} # Replace with the actual URL of your Authentication Service
          predicates:
            - Path=/api/auth/v1/**
          filters:
            - RewritePath=/api/auth/v1/(?<segment>.*), /api/v1/$\{segment}
            - CustomHeaderFilter

        - id: wallet-service
          uri: ${WALLET_SERVICE_URL} # Replace with the actual URL of your Wallet Service
          predicates:
            - Path=/api/wallet/v1/**
          filters:
            - RewritePath=/api/wallet/v1/(?<segment>.*), /api/v1/$\{segment}
            - CustomHeaderFilter

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL} # Replace with the actual URL of your Transfer Service
          predicates:
            - Path=/api/payment/v1/**
          filters:
            - RewritePath=/api/payment/v1/(?<segment>.*), /api/v1/$\{segment}
            - CustomHeaderFilter

        - id: transaction-history-service
          uri: ${TRANSACTION_SERVICE_URL} # Replace with the actual URL of your Transaction History Service
          predicates:
            - Path=/api/transaction/**
          filters:
            - RewritePath=/api/transaction/v1/(?<segment>.*), /api/v1/$\{segment}
            - CustomHeaderFilter