INSERT INTO WLT_USER(ID, EMAIL, PASSWORD_HASH, ENABLED)
VALUES(1, 'admin@gmail.com', '$2a$10$2kxpRTPLxaLhMc3sz1rjxenIPJl6bL4RfOGLzU4tMyfFgTeC.wTpi', true)
    ON CONFLICT (EMAIL) DO NOTHING;

INSERT INTO USER_ROLES(USER_ID, ROLES)
VALUES(1, 'ADMIN');