create table IF NOT EXISTS wlt_user
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6),
    created_by    varchar(255),
    email         varchar(255) not null
        constraint ukvfgsaeenxt58jeknlbcy2of0
            unique,
    enabled       boolean      not null,
    password_hash varchar(255) not null,
    updated_at    timestamp(6),
    updated_by    varchar(255)
);

alter table wlt_user
    owner to admin;

create table if not exists wlt_permission
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
        constraint ukkwlem2sn1b4udwlbj2mbnaeua
            unique
);

alter table wlt_permission
    owner to admin;

create table if not exists wlt_role
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
        constraint ukmpumc14i9p28txk2uj894jwwl
            unique
);

alter table wlt_role
    owner to admin;

create table if not exists wlt_role_permission
(
    role_id       bigint not null
        constraint fk5buoj4pyv1pjwqw8vnnjiu9dr
            references wlt_role,
    permission_id bigint not null
        constraint fkdr31iljxlfjopoa2p5v5c29k0
            references wlt_permission,
    primary key (role_id, permission_id)
);

alter table wlt_role_permission
    owner to admin;

create table if not exists wlt_user_role
(
    user_id bigint not null
        constraint fktlpw31qh1gna695457sa2r5ai
            references wlt_user,
    role_id bigint not null
        constraint fk4oi7y00lk89xpwvrg5ga2xsu2
            references wlt_role,
    primary key (user_id, role_id)
);

alter table wlt_user_role
    owner to admin;

create table if not exists wlt_session
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    created_by varchar(255),
    expires_at timestamp(6),
    ip         varchar(255),
    status     varchar(255),
    token      varchar(255),
    user_agent varchar(255),
    user_id    bigint
);

alter table wlt_session
    owner to admin;