rabbitmq:
  exchange:
    gift-code: gift-code.exchange
    fund-transfer: fund-transfer.exchange
    wallet: wallet.exchange
    transaction:
      history: transaction.history.exchange
    balance-update: balance-update.exchange
  queue:
    gift-code:
      redeem: gift-code.redeem.queue
    fund-transfer: fund-transfer.queue
    init:
      fund-transfer: init.fund-transfer.queue
    wallet: wallet.update.queue
    transaction:
      history: transaction.history.queue
    balance-update: balance-update.queue
  routing-key:
    gift-code:
      redeem: gift-code.redeem.routing-key
    fund-transfer: fund-transfer.routing-key
    wallet: wallet.update.routing-key
    transaction:
      history: transaction.history.routing-key
    balance-update: balance-update.routing-key

spring:
  sql:
    init:
      mode: always
  application:
    name: payment-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

wallet:
  service:
    base-url: ${WALLET_SERVICE_URL}