create table if not exists wlt_giftcode
(
    id               bigint generated by default as identity
        primary key,
    amount           numeric(38, 2),
    ccy              varchar(255),
    created_at       timestamp(6),
    created_by       varchar(255),
    expiry_date_time timestamp(6),
    gift_code        varchar(255) not null
        constraint uk7m78em8uvf4cejasmab2hfc2p
            unique,
    is_redeemed      varchar(255),
    redeemed_by      bigint,
    updated_at       timestamp(6),
    updated_by       varchar(255)
);

alter table wlt_giftcode
    owner to admin;

create table if not exists wlt_exchange_rate
(
    id         bigint not null
        primary key,
    cr_ccy     varchar(255),
    created_at timestamp(6),
    created_by varchar(255),
    dr_ccy     varchar(255),
    rate       real,
    updated_at timestamp(6),
    updated_by varchar(255)
);

alter table wlt_exchange_rate
    owner to admin;

create table if not exists wlt_transaction
(
    id                 bigint generated by default as identity
        primary key,
    amount             numeric(38, 2),
    ccy                varchar(255),
    cr_ccy             varchar(255),
    cr_wallet_id       bigint,
    created_at         timestamp(6),
    created_by         varchar(255),
    description        varchar(255),
    dr_ccy             varchar(255),
    dr_wallet_id       bigint,
    exchange_rate      numeric(38, 2),
    payment_ref_no     varchar(255)
        constraint ukl35pq351fdixjnse28eko05gp
            unique,
    status             varchar(255),
    transaction_ref_no varchar(255)
        constraint ukbppkkrmahv6kk377jkxfd8jq8
            unique,
    updated_at         timestamp(6),
    updated_by         varchar(255)
);

alter table wlt_transaction
    owner to admin;