rabbitmq:
  exchange:
    transaction:
      history: transaction.history.exchange
  queue:
    transaction:
      history: transaction.history.queue
  routing-key:
    transaction:
      history: transaction.history.routing-key

spring:
  sql:
    init:
      mode: always
  application:
    name: transaction-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
