create table if not exists wlt_transaction_history
(
    id                 bigint generated by default as identity
        primary key,
    amount             numeric(38, 2),
    cr_amount          numeric(38, 2),
    cr_ccy             varchar(255),
    cr_wallet_id       bigint,
    dr_amount          numeric(38, 2),
    dr_ccy             varchar(255),
    dr_wallet_id       bigint,
    exchange_rate      numeric(38, 2),
    save_timestamp     timestamp(6),
    status             varchar(255),
    transaction_ref_no varchar(255),
    transaction_type   varchar(255),
    txn_ccy            varchar(255),
    user_id            bigint
);

alter table wlt_transaction_history
    owner to admin;